//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.19 at 03:10:07 PM CST 
//


package com.eqinson.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Animals complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Animals">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="animal" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="animalName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="animalType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Animals", propOrder = {
    "animal"
})
public class Animals {

    @XmlElement(required = true)
    protected List<Animals.Animal> animal;

    /**
     * Gets the value of the animal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the animal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnimal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Animals.Animal }
     * 
     * 
     */
    public List<Animals.Animal> getAnimal() {
        if (animal == null) {
            animal = new ArrayList<Animals.Animal>();
        }
        return this.animal;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="animalName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="animalType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "animalName",
        "animalType"
    })
    public static class Animal {

        @XmlElement(required = true)
        protected String animalName;
        @XmlElement(required = true)
        protected String animalType;

        /**
         * Gets the value of the animalName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnimalName() {
            return animalName;
        }

        /**
         * Sets the value of the animalName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnimalName(String value) {
            this.animalName = value;
        }

        /**
         * Gets the value of the animalType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnimalType() {
            return animalType;
        }

        /**
         * Sets the value of the animalType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnimalType(String value) {
            this.animalType = value;
        }

    }

}
