package com.demo.ibatis.dao;

import com.demo.ibatis.beans.Sms;
import com.demo.ibatis.beans.SmsExample;
import java.sql.SQLException;
import java.util.List;

public interface SmsDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Integer insert(Sms record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeyWithoutBLOBs(Sms record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeyWithBLOBs(Sms record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeySelective(Sms record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<Sms> selectByExampleWithoutBLOBs(SmsExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<Sms> selectByExampleWithBLOBs(SmsExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Sms selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByExample(SmsExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int countByExample(SmsExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleSelective(Sms record, SmsExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleWithBLOBs(Sms record, SmsExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table sms
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleWithoutBLOBs(Sms record, SmsExample example) throws SQLException;
}