package com.demo.ibatis.dao;

import com.demo.ibatis.beans.User;
import com.demo.ibatis.beans.UserExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class UserDAOImpl implements UserDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public UserDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setSqlMapClient(SqlMapClient sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public SqlMapClient getSqlMapClient() {
		return sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer insert(User record) throws SQLException {
		Object newKey = sqlMapClient.insert("user.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByPrimaryKey(User record) throws SQLException {
		int rows = sqlMapClient.update("user.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByPrimaryKeySelective(User record) throws SQLException {
		int rows = sqlMapClient.update("user.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	@SuppressWarnings("unchecked")
	public List<User> selectByExample(UserExample example) throws SQLException {
		List<User> list = (List<User>) sqlMapClient.queryForList("user.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public User selectByPrimaryKey(Integer id) throws SQLException {
		User key = new User();
		key.setId(id);
		User record = (User) sqlMapClient.queryForObject("user.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int deleteByExample(UserExample example) throws SQLException {
		int rows = sqlMapClient.delete("user.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		User key = new User();
		key.setId(id);
		int rows = sqlMapClient.delete("user.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int countByExample(UserExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("user.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByExampleSelective(User record, UserExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("user.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByExample(User record, UserExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("user.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private static class UpdateByExampleParms extends UserExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}