//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.19 at 03:10:07 PM CST 
//


package com.eqinson.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eqinson.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Zoo_QNAME = new QName("", "zoo");
    private final static QName _Comment_QNAME = new QName("", "comment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eqinson.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Animals }
     * 
     */
    public Animals createAnimals() {
        return new Animals();
    }

    /**
     * Create an instance of {@link ZooInfo }
     * 
     */
    public ZooInfo createZooInfo() {
        return new ZooInfo();
    }

    /**
     * Create an instance of {@link Animals.Animal }
     * 
     */
    public Animals.Animal createAnimalsAnimal() {
        return new Animals.Animal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZooInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zoo")
    public JAXBElement<ZooInfo> createZoo(ZooInfo value) {
        return new JAXBElement<ZooInfo>(_Zoo_QNAME, ZooInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

}
