package com.demo.ibatis.beans;

public class Sms {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column sms.id
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column sms.username
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String username;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column sms.sender
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String sender;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column sms.sendtime
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String sendtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column sms.isRead
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String isread;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column sms.message
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String message;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column sms.id
	 * 
	 * @return the value of sms.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column sms.id
	 * 
	 * @param id
	 *            the value for sms.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column sms.username
	 * 
	 * @return the value of sms.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column sms.username
	 * 
	 * @param username
	 *            the value for sms.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column sms.sender
	 * 
	 * @return the value of sms.sender
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getSender() {
		return sender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column sms.sender
	 * 
	 * @param sender
	 *            the value for sms.sender
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setSender(String sender) {
		this.sender = sender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column sms.sendtime
	 * 
	 * @return the value of sms.sendtime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getSendtime() {
		return sendtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column sms.sendtime
	 * 
	 * @param sendtime
	 *            the value for sms.sendtime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column sms.isRead
	 * 
	 * @return the value of sms.isRead
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getIsread() {
		return isread;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column sms.isRead
	 * 
	 * @param isread
	 *            the value for sms.isRead
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setIsread(String isread) {
		this.isread = isread;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column sms.message
	 * 
	 * @return the value of sms.message
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column sms.message
	 * 
	 * @param message
	 *            the value for sms.message
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setMessage(String message) {
		this.message = message;
	}
}