package com.demo.ibatis.beans;

public class Address {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.id
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.username
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String username;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.name
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.sex
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String sex;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.mobile
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String mobile;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.email
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String email;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.qq
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String qq;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.company
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String company;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.address
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String address;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column address.postcode
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String postcode;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.id
	 * 
	 * @return the value of address.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.id
	 * 
	 * @param id
	 *            the value for address.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.username
	 * 
	 * @return the value of address.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.username
	 * 
	 * @param username
	 *            the value for address.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.name
	 * 
	 * @return the value of address.name
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.name
	 * 
	 * @param name
	 *            the value for address.name
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.sex
	 * 
	 * @return the value of address.sex
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.sex
	 * 
	 * @param sex
	 *            the value for address.sex
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.mobile
	 * 
	 * @return the value of address.mobile
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.mobile
	 * 
	 * @param mobile
	 *            the value for address.mobile
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.email
	 * 
	 * @return the value of address.email
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.email
	 * 
	 * @param email
	 *            the value for address.email
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.qq
	 * 
	 * @return the value of address.qq
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.qq
	 * 
	 * @param qq
	 *            the value for address.qq
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.company
	 * 
	 * @return the value of address.company
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.company
	 * 
	 * @param company
	 *            the value for address.company
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.address
	 * 
	 * @return the value of address.address
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.address
	 * 
	 * @param address
	 *            the value for address.address
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column address.postcode
	 * 
	 * @return the value of address.postcode
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getPostcode() {
		return postcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column address.postcode
	 * 
	 * @param postcode
	 *            the value for address.postcode
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}
}