package com.demo.ibatis.beans;

public class Meeting {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column meeting.id
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column meeting.sender
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String sender;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column meeting.starttime
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String starttime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column meeting.endtime
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String endtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column meeting.address
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String address;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column meeting.title
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String title;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column meeting.content
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String content;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column meeting.id
	 * 
	 * @return the value of meeting.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column meeting.id
	 * 
	 * @param id
	 *            the value for meeting.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column meeting.sender
	 * 
	 * @return the value of meeting.sender
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getSender() {
		return sender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column meeting.sender
	 * 
	 * @param sender
	 *            the value for meeting.sender
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setSender(String sender) {
		this.sender = sender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column meeting.starttime
	 * 
	 * @return the value of meeting.starttime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column meeting.starttime
	 * 
	 * @param starttime
	 *            the value for meeting.starttime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column meeting.endtime
	 * 
	 * @return the value of meeting.endtime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column meeting.endtime
	 * 
	 * @param endtime
	 *            the value for meeting.endtime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column meeting.address
	 * 
	 * @return the value of meeting.address
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column meeting.address
	 * 
	 * @param address
	 *            the value for meeting.address
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column meeting.title
	 * 
	 * @return the value of meeting.title
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column meeting.title
	 * 
	 * @param title
	 *            the value for meeting.title
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column meeting.content
	 * 
	 * @return the value of meeting.content
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column meeting.content
	 * 
	 * @param content
	 *            the value for meeting.content
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setContent(String content) {
		this.content = content;
	}
}