package com.demo.ibatis.beans;

public class Notice {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column notice.id
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column notice.sender
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String sender;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column notice.title
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String title;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column notice.sendtime
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String sendtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column notice.content
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String content;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column notice.id
	 * 
	 * @return the value of notice.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column notice.id
	 * 
	 * @param id
	 *            the value for notice.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column notice.sender
	 * 
	 * @return the value of notice.sender
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getSender() {
		return sender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column notice.sender
	 * 
	 * @param sender
	 *            the value for notice.sender
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setSender(String sender) {
		this.sender = sender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column notice.title
	 * 
	 * @return the value of notice.title
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column notice.title
	 * 
	 * @param title
	 *            the value for notice.title
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column notice.sendtime
	 * 
	 * @return the value of notice.sendtime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getSendtime() {
		return sendtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column notice.sendtime
	 * 
	 * @param sendtime
	 *            the value for notice.sendtime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column notice.content
	 * 
	 * @return the value of notice.content
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column notice.content
	 * 
	 * @param content
	 *            the value for notice.content
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setContent(String content) {
		this.content = content;
	}
}