package com.demo.ibatis.beans;

public class Schedule {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column schedule.id
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column schedule.username
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String username;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column schedule.year
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer year;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column schedule.month
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer month;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column schedule.day
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer day;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column schedule.plan
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String plan;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column schedule.id
	 * 
	 * @return the value of schedule.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column schedule.id
	 * 
	 * @param id
	 *            the value for schedule.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column schedule.username
	 * 
	 * @return the value of schedule.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column schedule.username
	 * 
	 * @param username
	 *            the value for schedule.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column schedule.year
	 * 
	 * @return the value of schedule.year
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getYear() {
		return year;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column schedule.year
	 * 
	 * @param year
	 *            the value for schedule.year
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column schedule.month
	 * 
	 * @return the value of schedule.month
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getMonth() {
		return month;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column schedule.month
	 * 
	 * @param month
	 *            the value for schedule.month
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setMonth(Integer month) {
		this.month = month;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column schedule.day
	 * 
	 * @return the value of schedule.day
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getDay() {
		return day;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column schedule.day
	 * 
	 * @param day
	 *            the value for schedule.day
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setDay(Integer day) {
		this.day = day;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column schedule.plan
	 * 
	 * @return the value of schedule.plan
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getPlan() {
		return plan;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column schedule.plan
	 * 
	 * @param plan
	 *            the value for schedule.plan
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setPlan(String plan) {
		this.plan = plan;
	}
}