package com.demo.ibatis.beans;

public class User {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user.id
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user.username
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String username;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user.password
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String password;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user.email
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String email;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user.id
	 * 
	 * @return the value of user.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user.id
	 * 
	 * @param id
	 *            the value for user.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user.username
	 * 
	 * @return the value of user.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user.username
	 * 
	 * @param username
	 *            the value for user.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user.password
	 * 
	 * @return the value of user.password
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user.password
	 * 
	 * @param password
	 *            the value for user.password
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user.email
	 * 
	 * @return the value of user.email
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user.email
	 * 
	 * @param email
	 *            the value for user.email
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}