package com.demo.ibatis.beans;

public class Worklog {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column worklog.id
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column worklog.username
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String username;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column worklog.year
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer year;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column worklog.month
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer month;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column worklog.day
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private Integer day;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column worklog.title
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String title;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column worklog.logtime
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String logtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column worklog.description
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private String description;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column worklog.id
	 * 
	 * @return the value of worklog.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column worklog.id
	 * 
	 * @param id
	 *            the value for worklog.id
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column worklog.username
	 * 
	 * @return the value of worklog.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column worklog.username
	 * 
	 * @param username
	 *            the value for worklog.username
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column worklog.year
	 * 
	 * @return the value of worklog.year
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getYear() {
		return year;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column worklog.year
	 * 
	 * @param year
	 *            the value for worklog.year
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column worklog.month
	 * 
	 * @return the value of worklog.month
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getMonth() {
		return month;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column worklog.month
	 * 
	 * @param month
	 *            the value for worklog.month
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setMonth(Integer month) {
		this.month = month;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column worklog.day
	 * 
	 * @return the value of worklog.day
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer getDay() {
		return day;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column worklog.day
	 * 
	 * @param day
	 *            the value for worklog.day
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setDay(Integer day) {
		this.day = day;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column worklog.title
	 * 
	 * @return the value of worklog.title
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column worklog.title
	 * 
	 * @param title
	 *            the value for worklog.title
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column worklog.logtime
	 * 
	 * @return the value of worklog.logtime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getLogtime() {
		return logtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column worklog.logtime
	 * 
	 * @param logtime
	 *            the value for worklog.logtime
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setLogtime(String logtime) {
		this.logtime = logtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column worklog.description
	 * 
	 * @return the value of worklog.description
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column worklog.description
	 * 
	 * @param description
	 *            the value for worklog.description
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}