package com.demo.ibatis.dao;

import com.demo.ibatis.beans.Notice;
import com.demo.ibatis.beans.NoticeExample;
import java.sql.SQLException;
import java.util.List;

public interface NoticeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Integer insert(Notice record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeyWithoutBLOBs(Notice record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeyWithBLOBs(Notice record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeySelective(Notice record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<Notice> selectByExampleWithoutBLOBs(NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<Notice> selectByExampleWithBLOBs(NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Notice selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByExample(NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int countByExample(NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleSelective(Notice record, NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleWithBLOBs(Notice record, NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table notice
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleWithoutBLOBs(Notice record, NoticeExample example) throws SQLException;
}