package com.demo.ibatis.dao;

import com.demo.ibatis.beans.Schedule;
import com.demo.ibatis.beans.ScheduleExample;
import java.sql.SQLException;
import java.util.List;

public interface ScheduleDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Integer insert(Schedule record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeyWithoutBLOBs(Schedule record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeyWithBLOBs(Schedule record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeySelective(Schedule record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<Schedule> selectByExampleWithoutBLOBs(ScheduleExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<Schedule> selectByExampleWithBLOBs(ScheduleExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Schedule selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByExample(ScheduleExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int countByExample(ScheduleExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleSelective(Schedule record, ScheduleExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleWithBLOBs(Schedule record, ScheduleExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table schedule
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleWithoutBLOBs(Schedule record, ScheduleExample example) throws SQLException;
}