package com.demo.ibatis.dao;

import com.demo.ibatis.beans.User;
import com.demo.ibatis.beans.UserExample;
import java.sql.SQLException;
import java.util.List;

public interface UserDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Integer insert(User record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKey(User record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeySelective(User record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<User> selectByExample(UserExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	User selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByExample(UserExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int countByExample(UserExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleSelective(User record, UserExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExample(User record, UserExample example) throws SQLException;
}