package com.demo.ibatis.dao;

import com.demo.ibatis.beans.Worklog;
import com.demo.ibatis.beans.WorklogExample;
import java.sql.SQLException;
import java.util.List;

public interface WorklogDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Integer insert(Worklog record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeyWithoutBLOBs(Worklog record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeyWithBLOBs(Worklog record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByPrimaryKeySelective(Worklog record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<Worklog> selectByExampleWithoutBLOBs(WorklogExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	List<Worklog> selectByExampleWithBLOBs(WorklogExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	Worklog selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByExample(WorklogExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int countByExample(WorklogExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleSelective(Worklog record, WorklogExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleWithBLOBs(Worklog record, WorklogExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	int updateByExampleWithoutBLOBs(Worklog record, WorklogExample example) throws SQLException;
}