package com.demo.ibatis.dao;

import com.demo.ibatis.beans.Worklog;
import com.demo.ibatis.beans.WorklogExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class WorklogDAOImpl implements WorklogDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public WorklogDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public void setSqlMapClient(SqlMapClient sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public SqlMapClient getSqlMapClient() {
		return sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Integer insert(Worklog record) throws SQLException {
		Object newKey = sqlMapClient.insert("worklog.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByPrimaryKeyWithoutBLOBs(Worklog record) throws SQLException {
		int rows = sqlMapClient.update("worklog.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByPrimaryKeyWithBLOBs(Worklog record) throws SQLException {
		int rows = sqlMapClient.update("worklog.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByPrimaryKeySelective(Worklog record) throws SQLException {
		int rows = sqlMapClient.update("worklog.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	@SuppressWarnings("unchecked")
	public List<Worklog> selectByExampleWithoutBLOBs(WorklogExample example) throws SQLException {
		List<Worklog> list = (List<Worklog>) sqlMapClient.queryForList("worklog.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	@SuppressWarnings("unchecked")
	public List<Worklog> selectByExampleWithBLOBs(WorklogExample example) throws SQLException {
		List<Worklog> list = (List<Worklog>) sqlMapClient
				.queryForList("worklog.abatorgenerated_selectByExampleWithBLOBs", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public Worklog selectByPrimaryKey(Integer id) throws SQLException {
		Worklog key = new Worklog();
		key.setId(id);
		Worklog record = (Worklog) sqlMapClient.queryForObject("worklog.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int deleteByExample(WorklogExample example) throws SQLException {
		int rows = sqlMapClient.delete("worklog.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Worklog key = new Worklog();
		key.setId(id);
		int rows = sqlMapClient.delete("worklog.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int countByExample(WorklogExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("worklog.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByExampleSelective(Worklog record, WorklogExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("worklog.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByExampleWithBLOBs(Worklog record, WorklogExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("worklog.abatorgenerated_updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	public int updateByExampleWithoutBLOBs(Worklog record, WorklogExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("worklog.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table worklog
	 * 
	 * @abatorgenerated Wed Dec 03 13:46:53 CST 2008
	 */
	private static class UpdateByExampleParms extends WorklogExample {
		private Object record;

		public UpdateByExampleParms(Object record, WorklogExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}